module.exports = {
  pathData: "",
  settings: {
    version: NaN,
    artist: "",
    song: "",
    author: "",
    separateCountdownTime: false,
    songFilename: "",
    bpm: NaN,
    volume: NaN,
    offset: NaN,
    pitch: NaN,
    hitsound: "",
    hitsoundVolume: NaN,
    trackColorType: "",
    trackColor: "",
    secondaryTrackColor: "",
    trackColorAnimDuration: NaN,
    trackColorPulse: "",
    trackPulseLength: NaN,
    trackStyle: "",
    trackAnimation: "",
    beatsAhead: NaN,
    trackDisappearAnimation: "",
    beatsBehind: NaN,
    backgroundColor: "",
    bgImage: "",
    bgImageColor: "",
    parallax: [NaN, NaN],
    bgDisplayMode: "",
    lockRot: false,
    loopBG: false,
    unscaledSize: NaN,
    relativeTo: "",
    position: [NaN, NaN],
    rotation: NaN,
    zoom: NaN,
    bgVideo: "",
    loopVideo: false,
    vidOffset: NaN,
    floorIconOutlines: false,
    stickToFloors: false,
    planetEase: "",
    planetEaseParts: NaN,
  },
  actions: [],
};
